### ISSUE TITLE
Values as Measurements

### ISSUE THREAD

**Issue by fabiobrolo** [dmslabsbr/smsUps#7]
Hi. Is it possible to enhance the code to treat the values as measurements?
Nowadays the values in historic are presented like strings and not as numeric values/measurements:
![image](https://user-images.githubusercontent.com/91396121/146557256-35f22d78-07af-4172-92f4-512f1d17228f.png)

**Comment by marceloaf** [comment]
Bom dia, Fabio! Tudo bem? Não sou o desenvolvedor desse add-on mas acho que consigo te ajudar. Não tem a ver com o código do addon e sim com uma característica do Home Assistant. Você precisa definir uma unidade de medida para este sensor para que o histórico passe a ser considerado como numérico. 

https://www.home-assistant.io/lovelace/history-graph/

Uma vez defiinda a unidade você verá algo como no gráfico abaixo:

![image](https://user-images.githubusercontent.com/11551691/146561040-2f5b9382-bf77-41a0-8382-d8f01462df5f.png)

**Comment by fabiobrolo** [comment]
Talvez no código esteja faltando a definição do state_class.
Para contornar o "problema", tive que incluir as seguintes entradas no
arquivo customize.yaml:

sensor.sms_01_inputvac:
  state_class: measurement
  unit_of_measurement: V
  device_class: voltage
sensor.sms_01_outputvac:
  state_class: measurement
  unit_of_measurement: V
  device_class: voltage
sensor.sms_01_batterylevel:
  state_class: measurement
  device_class: battery
  unit_of_measurement: "%"
sensor.sms_01_outputpower:
  state_class: measurement
  unit_of_measurement: W
  device_class: power
sensor.sms_01_temperaturec:
  state_class: measurement
  unit_of_measurement: °C
  device_class: temperature
sensor.sms_01_outputhz:
  state_class: measurement
  device_class: frequency
  unit_of_measurement: "Hz"

**Comment by marceloaf** [comment]
Fiz de maneira semelhante. A única diferença é que não coloquei o state_class nem o device_class. Apenas unit_of_measurement.

![image](https://user-images.githubusercontent.com/11551691/146580492-496d71e2-4108-4429-9e8f-fed4746694f0.png)
