### ISSUE TITLE
'No UPS Data' generating No Energy Notification

### ISSUE THREAD

**Issue by fabiobrolo** [dmslabsbr/smsUps#8]
I don´t know why many times in a day it is displayed the following log messages SMS UPS BETA log window:

2022-01-13 13:49:15,775 - root - DEBUG - String error!
No UPS Data
2022-01-13 13:49:15,776 - root - DEBUG - No UPS Data
[{"entity_id": "persistent_notification.54543123", "state": "notifying", "attributes": {"title": "smsUPS - No energy!", "friendly_name": "smsUPS - No energy!", "message": "**ups_SMS_01**<BR>Running without energy for **0:00:04 seconds.**<BR><BR>Battery level: **1 %**<BR>Shutdown battery level: **30 %**<BR>Estimated shutdown time in **-1 day, 23:59:31**<BR><BR>*2022-01-13 13:49:15*<BR>*<sub><sup>by dmslabs</sup></sub>*"}, "last_changed": "2022-01-13T16:49:15.798673+00:00", "last_updated": "2022-01-13T16:49:15.798673+00:00", "context": {"id": "5bc839e09f7da65bccdf4097ba6f495c", "parent_id": null, "user_id": "4b582be08f484b88bdc073dcb9e530c6"}}]
batConsumo:  0.0
Erro na string
2022-01-13 13:49:20,526 - root - DEBUG - String error!
No UPS Data
2022-01-13 13:49:20,527 - root - DEBUG - No UPS Data
[{"entity_id": "persistent_notification.54543123", "state": "notifying", "attributes": {"title": "smsUPS - No energy!", "friendly_name": "smsUPS - No energy!", "message": "**ups_SMS_01**<BR>Running without energy for **0:00:09 seconds.**<BR><BR>Battery level: **1 %**<BR>Shutdown battery level: **30 %**<BR>Estimated shutdown time in **-1 day, 23:59:31**<BR><BR>*2022-01-13 13:49:20*<BR>*<sub><sup>by dmslabs</sup></sub>*"}, "last_changed": "2022-01-13T16:49:15.798673+00:00", "last_updated": "2022-01-13T16:49:20.619386+00:00", "context": {"id": "daf585d6d63c158f3a6dd7797a8fd545", "parent_id": null, "user_id": "4b582be08f484b88bdc073dcb9e530c6"}}]
[{"entity_id": "persistent_notification.54543124", "state": "notifying", "attributes": {"title": "smsUPS - Energy returned!", "friendly_name": "smsUPS - Energy returned!", "message": "**ups_SMS_01**<BR>Now battery is charging.<BR><BR>Battery level: **100 %**<BR>I ran without power for **0:00:14 seconds.**<BR><BR>*2022-01-13 13:49:25*<BR>*<sub><sup>by dmslabs</sup></sub>*"}, "last_changed": "2022-01-13T16:49:25.376572+00:00", "last_updated": "2022-01-13T16:49:25.376572+00:00", "context": {"id": "0f02a95dd6597ff7e1c5d710b938c063", "parent_id": null, "user_id": "4b582be08f484b88bdc073dcb9e530c6"}}]
Dados UPS Publicados...2022-01-13 13:48:45.652572

This is causing a lot of wrong notifications in my Home Assistant.
Do you have any idea in how to fix it?

**Comment by dmslabsbr** [comment]
When it's happened?

These messages are show when a power loss occurs.

Also, the UPS are sending wrong battery level. So I'm looking to correct it.

**Comment by fabiobrolo** [comment]
Randomly when the system is with energy without any power loss.

**Comment by dmslabsbr** [comment]
Which one is your UPS? Is it a SMS Manager III?

No UPS Data error look like an communication error between UPS and HA machine.  What is the cable size?  May be you could change usb cable.

Could you send add-on log ? http://xx.xx.xx.xx:8123/hassio/addon/yyyyyy_hassio_sms_ups/logs ?

**Comment by fabiobrolo** [comment]
Is SMS Manager III of 700KVA. I´m using the original USB cable that comes with the UPS.
Follow attached the complete log extracted using docker logs addon_xxxx_hassio_sms_ups.
I will try another cable and let you know
[addon_sms.log](https://github.com/dmslabsbr/smsUps/files/7872670/addon_sms.log)
.

**Comment by fabiobrolo** [comment]
I´ve changed my USB cable and the problem persists.

**Comment by dmslabsbr** [comment]
Hi, I push a new version, could you try and give a feedback?

**Comment by fabiobrolo** [comment]
Hi Daniel.
The problem is now fixed.
Thank you very much.
_______________________________
Fábio Brolo
[11] 98426 1371 (Whatsapp)
